/* NO INCLUDE */
#ifndef GLSLCPP
#define GLSLCPP
#ifdef __cplusplus

// vecx
// clang-format off
struct vec2 {
    static constexpr int dim=2;
    float x;
    float r;
    float s;
    float y;
    float g;
    float t;
    vec2& xx;
    vec2& rr;
    vec2& ss;
    vec2& xy;
    vec2& rg;
    vec2& st;
    vec2& yx;
    vec2& gr;
    vec2& ts;
    vec2& yy;
    vec2& gg;
    vec2& tt;
    vec2();
    explicit vec2(float);
    vec2(float, float);
    vec2(const ivec2&);
    vec2& operator=(const ivec2&);
    float operator[](const int);
    vec2& operator=(const vec2&);
    template<typename T> vec2& operator+=(const T&);
    template<typename T> vec2& operator-=(const T&);
    template<typename T> vec2& operator*=(const T&);
    template<typename T> vec2& operator/=(const T&);
};
vec2 operator-(const vec2&);
vec2 operator+(const vec2&, const vec2&);
vec2 operator-(const vec2&, const vec2&);
vec2 operator*(const vec2&, const vec2&);
vec2 operator/(const vec2&, const vec2&);
vec2 operator+(const float&, const vec2&);
vec2 operator-(const float&, const vec2&);
vec2 operator*(const float&, const vec2&);
vec2 operator/(const float&, const vec2&);
vec2 operator+(const double&, const vec2&);
vec2 operator-(const double&, const vec2&);
vec2 operator*(const double&, const vec2&);
vec2 operator/(const double&, const vec2&);
vec2 operator+(const int&  , const vec2&);
vec2 operator-(const int&  , const vec2&);
vec2 operator*(const int&  , const vec2&);
vec2 operator/(const int&  , const vec2&);
vec2 operator+(const vec2&, const float&);
vec2 operator-(const vec2&, const float&);
vec2 operator*(const vec2&, const float&);
vec2 operator/(const vec2&, const float&);
vec2 operator+(const vec2&, const double&);
vec2 operator-(const vec2&, const double&);
vec2 operator*(const vec2&, const double&);
vec2 operator/(const vec2&, const double&);
vec2 operator+(const vec2&, const int&  );
vec2 operator-(const vec2&, const int&  );
vec2 operator*(const vec2&, const int&  );
vec2 operator/(const vec2&, const int&  );
vec2 refract(const vec2&, const vec2&, float);
vec2 dFdx(const vec2&);
vec2 dFdy(const vec2&);
ivec2 floor(const vec2&);
vec2 fract(const vec2&);
vec2 exp2(const vec2&);
vec2 clamp(const vec2&, const vec2&, const vec2&);
vec2 clamp(const vec2&, const float&, const float&);
vec2 sin(const vec2&);
vec2 cos(const vec2&);struct vec3 {
    static constexpr int dim=3;
    float x;
    float r;
    float s;
    float y;
    float g;
    float t;
    float z;
    float b;
    float u;
    vec2& xx;
    vec2& rr;
    vec2& ss;
    vec2& xy;
    vec2& rg;
    vec2& st;
    vec2& xz;
    vec2& rb;
    vec2& su;
    vec2& yx;
    vec2& gr;
    vec2& ts;
    vec2& yy;
    vec2& gg;
    vec2& tt;
    vec2& yz;
    vec2& gb;
    vec2& tu;
    vec2& zx;
    vec2& br;
    vec2& us;
    vec2& zy;
    vec2& bg;
    vec2& ut;
    vec2& zz;
    vec2& bb;
    vec2& uu;
    vec3& xxx;
    vec3& rrr;
    vec3& sss;
    vec3& xxy;
    vec3& rrg;
    vec3& sst;
    vec3& xxz;
    vec3& rrb;
    vec3& ssu;
    vec3& xyx;
    vec3& rgr;
    vec3& sts;
    vec3& xyy;
    vec3& rgg;
    vec3& stt;
    vec3& xyz;
    vec3& rgb;
    vec3& stu;
    vec3& xzx;
    vec3& rbr;
    vec3& sus;
    vec3& xzy;
    vec3& rbg;
    vec3& sut;
    vec3& xzz;
    vec3& rbb;
    vec3& suu;
    vec3& yxx;
    vec3& grr;
    vec3& tss;
    vec3& yxy;
    vec3& grg;
    vec3& tst;
    vec3& yxz;
    vec3& grb;
    vec3& tsu;
    vec3& yyx;
    vec3& ggr;
    vec3& tts;
    vec3& yyy;
    vec3& ggg;
    vec3& ttt;
    vec3& yyz;
    vec3& ggb;
    vec3& ttu;
    vec3& yzx;
    vec3& gbr;
    vec3& tus;
    vec3& yzy;
    vec3& gbg;
    vec3& tut;
    vec3& yzz;
    vec3& gbb;
    vec3& tuu;
    vec3& zxx;
    vec3& brr;
    vec3& uss;
    vec3& zxy;
    vec3& brg;
    vec3& ust;
    vec3& zxz;
    vec3& brb;
    vec3& usu;
    vec3& zyx;
    vec3& bgr;
    vec3& uts;
    vec3& zyy;
    vec3& bgg;
    vec3& utt;
    vec3& zyz;
    vec3& bgb;
    vec3& utu;
    vec3& zzx;
    vec3& bbr;
    vec3& uus;
    vec3& zzy;
    vec3& bbg;
    vec3& uut;
    vec3& zzz;
    vec3& bbb;
    vec3& uuu;
    vec3();
    explicit vec3(float);
    vec3(float, float, float);
    vec3(const ivec3&);
    vec3& operator=(const ivec3&);
    explicit vec3(vec2, float);
    explicit vec3(float, vec2);
    float operator[](const int);
    vec3& operator=(const vec3&);
    template<typename T> vec3& operator+=(const T&);
    template<typename T> vec3& operator-=(const T&);
    template<typename T> vec3& operator*=(const T&);
    template<typename T> vec3& operator/=(const T&);
};
vec3 operator-(const vec3&);
vec3 operator+(const vec3&, const vec3&);
vec3 operator-(const vec3&, const vec3&);
vec3 operator*(const vec3&, const vec3&);
vec3 operator/(const vec3&, const vec3&);
vec3 operator+(const float&, const vec3&);
vec3 operator-(const float&, const vec3&);
vec3 operator*(const float&, const vec3&);
vec3 operator/(const float&, const vec3&);
vec3 operator+(const double&, const vec3&);
vec3 operator-(const double&, const vec3&);
vec3 operator*(const double&, const vec3&);
vec3 operator/(const double&, const vec3&);
vec3 operator+(const int&  , const vec3&);
vec3 operator-(const int&  , const vec3&);
vec3 operator*(const int&  , const vec3&);
vec3 operator/(const int&  , const vec3&);
vec3 operator+(const vec3&, const float&);
vec3 operator-(const vec3&, const float&);
vec3 operator*(const vec3&, const float&);
vec3 operator/(const vec3&, const float&);
vec3 operator+(const vec3&, const double&);
vec3 operator-(const vec3&, const double&);
vec3 operator*(const vec3&, const double&);
vec3 operator/(const vec3&, const double&);
vec3 operator+(const vec3&, const int&  );
vec3 operator-(const vec3&, const int&  );
vec3 operator*(const vec3&, const int&  );
vec3 operator/(const vec3&, const int&  );
vec3 refract(const vec3&, const vec3&, float);
vec3 dFdx(const vec3&);
vec3 dFdy(const vec3&);
ivec3 floor(const vec3&);
vec3 fract(const vec3&);
vec3 exp2(const vec3&);
vec3 clamp(const vec3&, const vec3&, const vec3&);
vec3 clamp(const vec3&, const float&, const float&);
vec3 sin(const vec3&);
vec3 cos(const vec3&);struct vec4 {
    static constexpr int dim=4;
    float x;
    float r;
    float s;
    float y;
    float g;
    float t;
    float z;
    float b;
    float u;
    float w;
    float a;
    float v;
    vec2& xx;
    vec2& rr;
    vec2& ss;
    vec2& xy;
    vec2& rg;
    vec2& st;
    vec2& xz;
    vec2& rb;
    vec2& su;
    vec2& xw;
    vec2& ra;
    vec2& sv;
    vec2& yx;
    vec2& gr;
    vec2& ts;
    vec2& yy;
    vec2& gg;
    vec2& tt;
    vec2& yz;
    vec2& gb;
    vec2& tu;
    vec2& yw;
    vec2& ga;
    vec2& tv;
    vec2& zx;
    vec2& br;
    vec2& us;
    vec2& zy;
    vec2& bg;
    vec2& ut;
    vec2& zz;
    vec2& bb;
    vec2& uu;
    vec2& zw;
    vec2& ba;
    vec2& uv;
    vec2& wx;
    vec2& ar;
    vec2& vs;
    vec2& wy;
    vec2& ag;
    vec2& vt;
    vec2& wz;
    vec2& ab;
    vec2& vu;
    vec2& ww;
    vec2& aa;
    vec2& vv;
    vec3& xxx;
    vec3& rrr;
    vec3& sss;
    vec3& xxy;
    vec3& rrg;
    vec3& sst;
    vec3& xxz;
    vec3& rrb;
    vec3& ssu;
    vec3& xxw;
    vec3& rra;
    vec3& ssv;
    vec3& xyx;
    vec3& rgr;
    vec3& sts;
    vec3& xyy;
    vec3& rgg;
    vec3& stt;
    vec3& xyz;
    vec3& rgb;
    vec3& stu;
    vec3& xyw;
    vec3& rga;
    vec3& stv;
    vec3& xzx;
    vec3& rbr;
    vec3& sus;
    vec3& xzy;
    vec3& rbg;
    vec3& sut;
    vec3& xzz;
    vec3& rbb;
    vec3& suu;
    vec3& xzw;
    vec3& rba;
    vec3& suv;
    vec3& xwx;
    vec3& rar;
    vec3& svs;
    vec3& xwy;
    vec3& rag;
    vec3& svt;
    vec3& xwz;
    vec3& rab;
    vec3& svu;
    vec3& xww;
    vec3& raa;
    vec3& svv;
    vec3& yxx;
    vec3& grr;
    vec3& tss;
    vec3& yxy;
    vec3& grg;
    vec3& tst;
    vec3& yxz;
    vec3& grb;
    vec3& tsu;
    vec3& yxw;
    vec3& gra;
    vec3& tsv;
    vec3& yyx;
    vec3& ggr;
    vec3& tts;
    vec3& yyy;
    vec3& ggg;
    vec3& ttt;
    vec3& yyz;
    vec3& ggb;
    vec3& ttu;
    vec3& yyw;
    vec3& gga;
    vec3& ttv;
    vec3& yzx;
    vec3& gbr;
    vec3& tus;
    vec3& yzy;
    vec3& gbg;
    vec3& tut;
    vec3& yzz;
    vec3& gbb;
    vec3& tuu;
    vec3& yzw;
    vec3& gba;
    vec3& tuv;
    vec3& ywx;
    vec3& gar;
    vec3& tvs;
    vec3& ywy;
    vec3& gag;
    vec3& tvt;
    vec3& ywz;
    vec3& gab;
    vec3& tvu;
    vec3& yww;
    vec3& gaa;
    vec3& tvv;
    vec3& zxx;
    vec3& brr;
    vec3& uss;
    vec3& zxy;
    vec3& brg;
    vec3& ust;
    vec3& zxz;
    vec3& brb;
    vec3& usu;
    vec3& zxw;
    vec3& bra;
    vec3& usv;
    vec3& zyx;
    vec3& bgr;
    vec3& uts;
    vec3& zyy;
    vec3& bgg;
    vec3& utt;
    vec3& zyz;
    vec3& bgb;
    vec3& utu;
    vec3& zyw;
    vec3& bga;
    vec3& utv;
    vec3& zzx;
    vec3& bbr;
    vec3& uus;
    vec3& zzy;
    vec3& bbg;
    vec3& uut;
    vec3& zzz;
    vec3& bbb;
    vec3& uuu;
    vec3& zzw;
    vec3& bba;
    vec3& uuv;
    vec3& zwx;
    vec3& bar;
    vec3& uvs;
    vec3& zwy;
    vec3& bag;
    vec3& uvt;
    vec3& zwz;
    vec3& bab;
    vec3& uvu;
    vec3& zww;
    vec3& baa;
    vec3& uvv;
    vec3& wxx;
    vec3& arr;
    vec3& vss;
    vec3& wxy;
    vec3& arg;
    vec3& vst;
    vec3& wxz;
    vec3& arb;
    vec3& vsu;
    vec3& wxw;
    vec3& ara;
    vec3& vsv;
    vec3& wyx;
    vec3& agr;
    vec3& vts;
    vec3& wyy;
    vec3& agg;
    vec3& vtt;
    vec3& wyz;
    vec3& agb;
    vec3& vtu;
    vec3& wyw;
    vec3& aga;
    vec3& vtv;
    vec3& wzx;
    vec3& abr;
    vec3& vus;
    vec3& wzy;
    vec3& abg;
    vec3& vut;
    vec3& wzz;
    vec3& abb;
    vec3& vuu;
    vec3& wzw;
    vec3& aba;
    vec3& vuv;
    vec3& wwx;
    vec3& aar;
    vec3& vvs;
    vec3& wwy;
    vec3& aag;
    vec3& vvt;
    vec3& wwz;
    vec3& aab;
    vec3& vvu;
    vec3& www;
    vec3& aaa;
    vec3& vvv;
    vec4& xxxx;
    vec4& rrrr;
    vec4& ssss;
    vec4& xxxy;
    vec4& rrrg;
    vec4& ssst;
    vec4& xxxz;
    vec4& rrrb;
    vec4& sssu;
    vec4& xxxw;
    vec4& rrra;
    vec4& sssv;
    vec4& xxyx;
    vec4& rrgr;
    vec4& ssts;
    vec4& xxyy;
    vec4& rrgg;
    vec4& sstt;
    vec4& xxyz;
    vec4& rrgb;
    vec4& sstu;
    vec4& xxyw;
    vec4& rrga;
    vec4& sstv;
    vec4& xxzx;
    vec4& rrbr;
    vec4& ssus;
    vec4& xxzy;
    vec4& rrbg;
    vec4& ssut;
    vec4& xxzz;
    vec4& rrbb;
    vec4& ssuu;
    vec4& xxzw;
    vec4& rrba;
    vec4& ssuv;
    vec4& xxwx;
    vec4& rrar;
    vec4& ssvs;
    vec4& xxwy;
    vec4& rrag;
    vec4& ssvt;
    vec4& xxwz;
    vec4& rrab;
    vec4& ssvu;
    vec4& xxww;
    vec4& rraa;
    vec4& ssvv;
    vec4& xyxx;
    vec4& rgrr;
    vec4& stss;
    vec4& xyxy;
    vec4& rgrg;
    vec4& stst;
    vec4& xyxz;
    vec4& rgrb;
    vec4& stsu;
    vec4& xyxw;
    vec4& rgra;
    vec4& stsv;
    vec4& xyyx;
    vec4& rggr;
    vec4& stts;
    vec4& xyyy;
    vec4& rggg;
    vec4& sttt;
    vec4& xyyz;
    vec4& rggb;
    vec4& sttu;
    vec4& xyyw;
    vec4& rgga;
    vec4& sttv;
    vec4& xyzx;
    vec4& rgbr;
    vec4& stus;
    vec4& xyzy;
    vec4& rgbg;
    vec4& stut;
    vec4& xyzz;
    vec4& rgbb;
    vec4& stuu;
    vec4& xyzw;
    vec4& rgba;
    vec4& stuv;
    vec4& xywx;
    vec4& rgar;
    vec4& stvs;
    vec4& xywy;
    vec4& rgag;
    vec4& stvt;
    vec4& xywz;
    vec4& rgab;
    vec4& stvu;
    vec4& xyww;
    vec4& rgaa;
    vec4& stvv;
    vec4& xzxx;
    vec4& rbrr;
    vec4& suss;
    vec4& xzxy;
    vec4& rbrg;
    vec4& sust;
    vec4& xzxz;
    vec4& rbrb;
    vec4& susu;
    vec4& xzxw;
    vec4& rbra;
    vec4& susv;
    vec4& xzyx;
    vec4& rbgr;
    vec4& suts;
    vec4& xzyy;
    vec4& rbgg;
    vec4& sutt;
    vec4& xzyz;
    vec4& rbgb;
    vec4& sutu;
    vec4& xzyw;
    vec4& rbga;
    vec4& sutv;
    vec4& xzzx;
    vec4& rbbr;
    vec4& suus;
    vec4& xzzy;
    vec4& rbbg;
    vec4& suut;
    vec4& xzzz;
    vec4& rbbb;
    vec4& suuu;
    vec4& xzzw;
    vec4& rbba;
    vec4& suuv;
    vec4& xzwx;
    vec4& rbar;
    vec4& suvs;
    vec4& xzwy;
    vec4& rbag;
    vec4& suvt;
    vec4& xzwz;
    vec4& rbab;
    vec4& suvu;
    vec4& xzww;
    vec4& rbaa;
    vec4& suvv;
    vec4& xwxx;
    vec4& rarr;
    vec4& svss;
    vec4& xwxy;
    vec4& rarg;
    vec4& svst;
    vec4& xwxz;
    vec4& rarb;
    vec4& svsu;
    vec4& xwxw;
    vec4& rara;
    vec4& svsv;
    vec4& xwyx;
    vec4& ragr;
    vec4& svts;
    vec4& xwyy;
    vec4& ragg;
    vec4& svtt;
    vec4& xwyz;
    vec4& ragb;
    vec4& svtu;
    vec4& xwyw;
    vec4& raga;
    vec4& svtv;
    vec4& xwzx;
    vec4& rabr;
    vec4& svus;
    vec4& xwzy;
    vec4& rabg;
    vec4& svut;
    vec4& xwzz;
    vec4& rabb;
    vec4& svuu;
    vec4& xwzw;
    vec4& raba;
    vec4& svuv;
    vec4& xwwx;
    vec4& raar;
    vec4& svvs;
    vec4& xwwy;
    vec4& raag;
    vec4& svvt;
    vec4& xwwz;
    vec4& raab;
    vec4& svvu;
    vec4& xwww;
    vec4& raaa;
    vec4& svvv;
    vec4& yxxx;
    vec4& grrr;
    vec4& tsss;
    vec4& yxxy;
    vec4& grrg;
    vec4& tsst;
    vec4& yxxz;
    vec4& grrb;
    vec4& tssu;
    vec4& yxxw;
    vec4& grra;
    vec4& tssv;
    vec4& yxyx;
    vec4& grgr;
    vec4& tsts;
    vec4& yxyy;
    vec4& grgg;
    vec4& tstt;
    vec4& yxyz;
    vec4& grgb;
    vec4& tstu;
    vec4& yxyw;
    vec4& grga;
    vec4& tstv;
    vec4& yxzx;
    vec4& grbr;
    vec4& tsus;
    vec4& yxzy;
    vec4& grbg;
    vec4& tsut;
    vec4& yxzz;
    vec4& grbb;
    vec4& tsuu;
    vec4& yxzw;
    vec4& grba;
    vec4& tsuv;
    vec4& yxwx;
    vec4& grar;
    vec4& tsvs;
    vec4& yxwy;
    vec4& grag;
    vec4& tsvt;
    vec4& yxwz;
    vec4& grab;
    vec4& tsvu;
    vec4& yxww;
    vec4& graa;
    vec4& tsvv;
    vec4& yyxx;
    vec4& ggrr;
    vec4& ttss;
    vec4& yyxy;
    vec4& ggrg;
    vec4& ttst;
    vec4& yyxz;
    vec4& ggrb;
    vec4& ttsu;
    vec4& yyxw;
    vec4& ggra;
    vec4& ttsv;
    vec4& yyyx;
    vec4& gggr;
    vec4& ttts;
    vec4& yyyy;
    vec4& gggg;
    vec4& tttt;
    vec4& yyyz;
    vec4& gggb;
    vec4& tttu;
    vec4& yyyw;
    vec4& ggga;
    vec4& tttv;
    vec4& yyzx;
    vec4& ggbr;
    vec4& ttus;
    vec4& yyzy;
    vec4& ggbg;
    vec4& ttut;
    vec4& yyzz;
    vec4& ggbb;
    vec4& ttuu;
    vec4& yyzw;
    vec4& ggba;
    vec4& ttuv;
    vec4& yywx;
    vec4& ggar;
    vec4& ttvs;
    vec4& yywy;
    vec4& ggag;
    vec4& ttvt;
    vec4& yywz;
    vec4& ggab;
    vec4& ttvu;
    vec4& yyww;
    vec4& ggaa;
    vec4& ttvv;
    vec4& yzxx;
    vec4& gbrr;
    vec4& tuss;
    vec4& yzxy;
    vec4& gbrg;
    vec4& tust;
    vec4& yzxz;
    vec4& gbrb;
    vec4& tusu;
    vec4& yzxw;
    vec4& gbra;
    vec4& tusv;
    vec4& yzyx;
    vec4& gbgr;
    vec4& tuts;
    vec4& yzyy;
    vec4& gbgg;
    vec4& tutt;
    vec4& yzyz;
    vec4& gbgb;
    vec4& tutu;
    vec4& yzyw;
    vec4& gbga;
    vec4& tutv;
    vec4& yzzx;
    vec4& gbbr;
    vec4& tuus;
    vec4& yzzy;
    vec4& gbbg;
    vec4& tuut;
    vec4& yzzz;
    vec4& gbbb;
    vec4& tuuu;
    vec4& yzzw;
    vec4& gbba;
    vec4& tuuv;
    vec4& yzwx;
    vec4& gbar;
    vec4& tuvs;
    vec4& yzwy;
    vec4& gbag;
    vec4& tuvt;
    vec4& yzwz;
    vec4& gbab;
    vec4& tuvu;
    vec4& yzww;
    vec4& gbaa;
    vec4& tuvv;
    vec4& ywxx;
    vec4& garr;
    vec4& tvss;
    vec4& ywxy;
    vec4& garg;
    vec4& tvst;
    vec4& ywxz;
    vec4& garb;
    vec4& tvsu;
    vec4& ywxw;
    vec4& gara;
    vec4& tvsv;
    vec4& ywyx;
    vec4& gagr;
    vec4& tvts;
    vec4& ywyy;
    vec4& gagg;
    vec4& tvtt;
    vec4& ywyz;
    vec4& gagb;
    vec4& tvtu;
    vec4& ywyw;
    vec4& gaga;
    vec4& tvtv;
    vec4& ywzx;
    vec4& gabr;
    vec4& tvus;
    vec4& ywzy;
    vec4& gabg;
    vec4& tvut;
    vec4& ywzz;
    vec4& gabb;
    vec4& tvuu;
    vec4& ywzw;
    vec4& gaba;
    vec4& tvuv;
    vec4& ywwx;
    vec4& gaar;
    vec4& tvvs;
    vec4& ywwy;
    vec4& gaag;
    vec4& tvvt;
    vec4& ywwz;
    vec4& gaab;
    vec4& tvvu;
    vec4& ywww;
    vec4& gaaa;
    vec4& tvvv;
    vec4& zxxx;
    vec4& brrr;
    vec4& usss;
    vec4& zxxy;
    vec4& brrg;
    vec4& usst;
    vec4& zxxz;
    vec4& brrb;
    vec4& ussu;
    vec4& zxxw;
    vec4& brra;
    vec4& ussv;
    vec4& zxyx;
    vec4& brgr;
    vec4& usts;
    vec4& zxyy;
    vec4& brgg;
    vec4& ustt;
    vec4& zxyz;
    vec4& brgb;
    vec4& ustu;
    vec4& zxyw;
    vec4& brga;
    vec4& ustv;
    vec4& zxzx;
    vec4& brbr;
    vec4& usus;
    vec4& zxzy;
    vec4& brbg;
    vec4& usut;
    vec4& zxzz;
    vec4& brbb;
    vec4& usuu;
    vec4& zxzw;
    vec4& brba;
    vec4& usuv;
    vec4& zxwx;
    vec4& brar;
    vec4& usvs;
    vec4& zxwy;
    vec4& brag;
    vec4& usvt;
    vec4& zxwz;
    vec4& brab;
    vec4& usvu;
    vec4& zxww;
    vec4& braa;
    vec4& usvv;
    vec4& zyxx;
    vec4& bgrr;
    vec4& utss;
    vec4& zyxy;
    vec4& bgrg;
    vec4& utst;
    vec4& zyxz;
    vec4& bgrb;
    vec4& utsu;
    vec4& zyxw;
    vec4& bgra;
    vec4& utsv;
    vec4& zyyx;
    vec4& bggr;
    vec4& utts;
    vec4& zyyy;
    vec4& bggg;
    vec4& uttt;
    vec4& zyyz;
    vec4& bggb;
    vec4& uttu;
    vec4& zyyw;
    vec4& bgga;
    vec4& uttv;
    vec4& zyzx;
    vec4& bgbr;
    vec4& utus;
    vec4& zyzy;
    vec4& bgbg;
    vec4& utut;
    vec4& zyzz;
    vec4& bgbb;
    vec4& utuu;
    vec4& zyzw;
    vec4& bgba;
    vec4& utuv;
    vec4& zywx;
    vec4& bgar;
    vec4& utvs;
    vec4& zywy;
    vec4& bgag;
    vec4& utvt;
    vec4& zywz;
    vec4& bgab;
    vec4& utvu;
    vec4& zyww;
    vec4& bgaa;
    vec4& utvv;
    vec4& zzxx;
    vec4& bbrr;
    vec4& uuss;
    vec4& zzxy;
    vec4& bbrg;
    vec4& uust;
    vec4& zzxz;
    vec4& bbrb;
    vec4& uusu;
    vec4& zzxw;
    vec4& bbra;
    vec4& uusv;
    vec4& zzyx;
    vec4& bbgr;
    vec4& uuts;
    vec4& zzyy;
    vec4& bbgg;
    vec4& uutt;
    vec4& zzyz;
    vec4& bbgb;
    vec4& uutu;
    vec4& zzyw;
    vec4& bbga;
    vec4& uutv;
    vec4& zzzx;
    vec4& bbbr;
    vec4& uuus;
    vec4& zzzy;
    vec4& bbbg;
    vec4& uuut;
    vec4& zzzz;
    vec4& bbbb;
    vec4& uuuu;
    vec4& zzzw;
    vec4& bbba;
    vec4& uuuv;
    vec4& zzwx;
    vec4& bbar;
    vec4& uuvs;
    vec4& zzwy;
    vec4& bbag;
    vec4& uuvt;
    vec4& zzwz;
    vec4& bbab;
    vec4& uuvu;
    vec4& zzww;
    vec4& bbaa;
    vec4& uuvv;
    vec4& zwxx;
    vec4& barr;
    vec4& uvss;
    vec4& zwxy;
    vec4& barg;
    vec4& uvst;
    vec4& zwxz;
    vec4& barb;
    vec4& uvsu;
    vec4& zwxw;
    vec4& bara;
    vec4& uvsv;
    vec4& zwyx;
    vec4& bagr;
    vec4& uvts;
    vec4& zwyy;
    vec4& bagg;
    vec4& uvtt;
    vec4& zwyz;
    vec4& bagb;
    vec4& uvtu;
    vec4& zwyw;
    vec4& baga;
    vec4& uvtv;
    vec4& zwzx;
    vec4& babr;
    vec4& uvus;
    vec4& zwzy;
    vec4& babg;
    vec4& uvut;
    vec4& zwzz;
    vec4& babb;
    vec4& uvuu;
    vec4& zwzw;
    vec4& baba;
    vec4& uvuv;
    vec4& zwwx;
    vec4& baar;
    vec4& uvvs;
    vec4& zwwy;
    vec4& baag;
    vec4& uvvt;
    vec4& zwwz;
    vec4& baab;
    vec4& uvvu;
    vec4& zwww;
    vec4& baaa;
    vec4& uvvv;
    vec4& wxxx;
    vec4& arrr;
    vec4& vsss;
    vec4& wxxy;
    vec4& arrg;
    vec4& vsst;
    vec4& wxxz;
    vec4& arrb;
    vec4& vssu;
    vec4& wxxw;
    vec4& arra;
    vec4& vssv;
    vec4& wxyx;
    vec4& argr;
    vec4& vsts;
    vec4& wxyy;
    vec4& argg;
    vec4& vstt;
    vec4& wxyz;
    vec4& argb;
    vec4& vstu;
    vec4& wxyw;
    vec4& arga;
    vec4& vstv;
    vec4& wxzx;
    vec4& arbr;
    vec4& vsus;
    vec4& wxzy;
    vec4& arbg;
    vec4& vsut;
    vec4& wxzz;
    vec4& arbb;
    vec4& vsuu;
    vec4& wxzw;
    vec4& arba;
    vec4& vsuv;
    vec4& wxwx;
    vec4& arar;
    vec4& vsvs;
    vec4& wxwy;
    vec4& arag;
    vec4& vsvt;
    vec4& wxwz;
    vec4& arab;
    vec4& vsvu;
    vec4& wxww;
    vec4& araa;
    vec4& vsvv;
    vec4& wyxx;
    vec4& agrr;
    vec4& vtss;
    vec4& wyxy;
    vec4& agrg;
    vec4& vtst;
    vec4& wyxz;
    vec4& agrb;
    vec4& vtsu;
    vec4& wyxw;
    vec4& agra;
    vec4& vtsv;
    vec4& wyyx;
    vec4& aggr;
    vec4& vtts;
    vec4& wyyy;
    vec4& aggg;
    vec4& vttt;
    vec4& wyyz;
    vec4& aggb;
    vec4& vttu;
    vec4& wyyw;
    vec4& agga;
    vec4& vttv;
    vec4& wyzx;
    vec4& agbr;
    vec4& vtus;
    vec4& wyzy;
    vec4& agbg;
    vec4& vtut;
    vec4& wyzz;
    vec4& agbb;
    vec4& vtuu;
    vec4& wyzw;
    vec4& agba;
    vec4& vtuv;
    vec4& wywx;
    vec4& agar;
    vec4& vtvs;
    vec4& wywy;
    vec4& agag;
    vec4& vtvt;
    vec4& wywz;
    vec4& agab;
    vec4& vtvu;
    vec4& wyww;
    vec4& agaa;
    vec4& vtvv;
    vec4& wzxx;
    vec4& abrr;
    vec4& vuss;
    vec4& wzxy;
    vec4& abrg;
    vec4& vust;
    vec4& wzxz;
    vec4& abrb;
    vec4& vusu;
    vec4& wzxw;
    vec4& abra;
    vec4& vusv;
    vec4& wzyx;
    vec4& abgr;
    vec4& vuts;
    vec4& wzyy;
    vec4& abgg;
    vec4& vutt;
    vec4& wzyz;
    vec4& abgb;
    vec4& vutu;
    vec4& wzyw;
    vec4& abga;
    vec4& vutv;
    vec4& wzzx;
    vec4& abbr;
    vec4& vuus;
    vec4& wzzy;
    vec4& abbg;
    vec4& vuut;
    vec4& wzzz;
    vec4& abbb;
    vec4& vuuu;
    vec4& wzzw;
    vec4& abba;
    vec4& vuuv;
    vec4& wzwx;
    vec4& abar;
    vec4& vuvs;
    vec4& wzwy;
    vec4& abag;
    vec4& vuvt;
    vec4& wzwz;
    vec4& abab;
    vec4& vuvu;
    vec4& wzww;
    vec4& abaa;
    vec4& vuvv;
    vec4& wwxx;
    vec4& aarr;
    vec4& vvss;
    vec4& wwxy;
    vec4& aarg;
    vec4& vvst;
    vec4& wwxz;
    vec4& aarb;
    vec4& vvsu;
    vec4& wwxw;
    vec4& aara;
    vec4& vvsv;
    vec4& wwyx;
    vec4& aagr;
    vec4& vvts;
    vec4& wwyy;
    vec4& aagg;
    vec4& vvtt;
    vec4& wwyz;
    vec4& aagb;
    vec4& vvtu;
    vec4& wwyw;
    vec4& aaga;
    vec4& vvtv;
    vec4& wwzx;
    vec4& aabr;
    vec4& vvus;
    vec4& wwzy;
    vec4& aabg;
    vec4& vvut;
    vec4& wwzz;
    vec4& aabb;
    vec4& vvuu;
    vec4& wwzw;
    vec4& aaba;
    vec4& vvuv;
    vec4& wwwx;
    vec4& aaar;
    vec4& vvvs;
    vec4& wwwy;
    vec4& aaag;
    vec4& vvvt;
    vec4& wwwz;
    vec4& aaab;
    vec4& vvvu;
    vec4& wwww;
    vec4& aaaa;
    vec4& vvvv;
    vec4();
    explicit vec4(float);
    vec4(float, float, float, float);
    vec4(const ivec4&);
    vec4& operator=(const ivec4&);
    explicit vec4(vec3, float);
    explicit vec4(float, vec3);
    explicit vec4(vec2, float, float);
    explicit vec4(float, vec2, float);
    explicit vec4(float, float, vec2);
    float operator[](const int);
    vec4& operator=(const vec4&);
    template<typename T> vec4& operator+=(const T&);
    template<typename T> vec4& operator-=(const T&);
    template<typename T> vec4& operator*=(const T&);
    template<typename T> vec4& operator/=(const T&);
};
vec4 operator-(const vec4&);
vec4 operator+(const vec4&, const vec4&);
vec4 operator-(const vec4&, const vec4&);
vec4 operator*(const vec4&, const vec4&);
vec4 operator/(const vec4&, const vec4&);
vec4 operator+(const float&, const vec4&);
vec4 operator-(const float&, const vec4&);
vec4 operator*(const float&, const vec4&);
vec4 operator/(const float&, const vec4&);
vec4 operator+(const double&, const vec4&);
vec4 operator-(const double&, const vec4&);
vec4 operator*(const double&, const vec4&);
vec4 operator/(const double&, const vec4&);
vec4 operator+(const int&  , const vec4&);
vec4 operator-(const int&  , const vec4&);
vec4 operator*(const int&  , const vec4&);
vec4 operator/(const int&  , const vec4&);
vec4 operator+(const vec4&, const float&);
vec4 operator-(const vec4&, const float&);
vec4 operator*(const vec4&, const float&);
vec4 operator/(const vec4&, const float&);
vec4 operator+(const vec4&, const double&);
vec4 operator-(const vec4&, const double&);
vec4 operator*(const vec4&, const double&);
vec4 operator/(const vec4&, const double&);
vec4 operator+(const vec4&, const int&  );
vec4 operator-(const vec4&, const int&  );
vec4 operator*(const vec4&, const int&  );
vec4 operator/(const vec4&, const int&  );
vec4 refract(const vec4&, const vec4&, float);
vec4 dFdx(const vec4&);
vec4 dFdy(const vec4&);
ivec4 floor(const vec4&);
vec4 fract(const vec4&);
vec4 exp2(const vec4&);
vec4 clamp(const vec4&, const vec4&, const vec4&);
vec4 clamp(const vec4&, const float&, const float&);
vec4 sin(const vec4&);
vec4 cos(const vec4&);struct ivec2 {
    static constexpr int dim=2;
    int x;
    int r;
    int s;
    int y;
    int g;
    int t;
    ivec2& xx;
    ivec2& rr;
    ivec2& ss;
    ivec2& xy;
    ivec2& rg;
    ivec2& st;
    ivec2& yx;
    ivec2& gr;
    ivec2& ts;
    ivec2& yy;
    ivec2& gg;
    ivec2& tt;
    ivec2();
    explicit ivec2(int);
    ivec2(int, int);
    int operator[](const int);
    ivec2& operator=(const ivec2&);
    template<typename T> ivec2& operator+=(const T&);
    template<typename T> ivec2& operator-=(const T&);
    template<typename T> ivec2& operator*=(const T&);
    template<typename T> ivec2& operator/=(const T&);
};
ivec2 operator-(const ivec2&);
ivec2 operator+(const ivec2&, const ivec2&);
ivec2 operator-(const ivec2&, const ivec2&);
ivec2 operator*(const ivec2&, const ivec2&);
ivec2 operator/(const ivec2&, const ivec2&);
ivec2 operator+(const float&, const ivec2&);
ivec2 operator-(const float&, const ivec2&);
ivec2 operator*(const float&, const ivec2&);
ivec2 operator/(const float&, const ivec2&);
ivec2 operator+(const double&, const ivec2&);
ivec2 operator-(const double&, const ivec2&);
ivec2 operator*(const double&, const ivec2&);
ivec2 operator/(const double&, const ivec2&);
ivec2 operator+(const int&  , const ivec2&);
ivec2 operator-(const int&  , const ivec2&);
ivec2 operator*(const int&  , const ivec2&);
ivec2 operator/(const int&  , const ivec2&);
ivec2 operator+(const ivec2&, const float&);
ivec2 operator-(const ivec2&, const float&);
ivec2 operator*(const ivec2&, const float&);
ivec2 operator/(const ivec2&, const float&);
ivec2 operator+(const ivec2&, const double&);
ivec2 operator-(const ivec2&, const double&);
ivec2 operator*(const ivec2&, const double&);
ivec2 operator/(const ivec2&, const double&);
ivec2 operator+(const ivec2&, const int&  );
ivec2 operator-(const ivec2&, const int&  );
ivec2 operator*(const ivec2&, const int&  );
ivec2 operator/(const ivec2&, const int&  );
ivec2 refract(const ivec2&, const ivec2&, float);
ivec2 dFdx(const ivec2&);
ivec2 dFdy(const ivec2&);
ivec2 exp2(const ivec2&);
ivec2 clamp(const ivec2&, const ivec2&, const ivec2&);
ivec2 clamp(const ivec2&, const float&, const float&);
ivec2 sin(const ivec2&);
ivec2 cos(const ivec2&);struct ivec3 {
    static constexpr int dim=3;
    int x;
    int r;
    int s;
    int y;
    int g;
    int t;
    int z;
    int b;
    int u;
    ivec2& xx;
    ivec2& rr;
    ivec2& ss;
    ivec2& xy;
    ivec2& rg;
    ivec2& st;
    ivec2& xz;
    ivec2& rb;
    ivec2& su;
    ivec2& yx;
    ivec2& gr;
    ivec2& ts;
    ivec2& yy;
    ivec2& gg;
    ivec2& tt;
    ivec2& yz;
    ivec2& gb;
    ivec2& tu;
    ivec2& zx;
    ivec2& br;
    ivec2& us;
    ivec2& zy;
    ivec2& bg;
    ivec2& ut;
    ivec2& zz;
    ivec2& bb;
    ivec2& uu;
    ivec3& xxx;
    ivec3& rrr;
    ivec3& sss;
    ivec3& xxy;
    ivec3& rrg;
    ivec3& sst;
    ivec3& xxz;
    ivec3& rrb;
    ivec3& ssu;
    ivec3& xyx;
    ivec3& rgr;
    ivec3& sts;
    ivec3& xyy;
    ivec3& rgg;
    ivec3& stt;
    ivec3& xyz;
    ivec3& rgb;
    ivec3& stu;
    ivec3& xzx;
    ivec3& rbr;
    ivec3& sus;
    ivec3& xzy;
    ivec3& rbg;
    ivec3& sut;
    ivec3& xzz;
    ivec3& rbb;
    ivec3& suu;
    ivec3& yxx;
    ivec3& grr;
    ivec3& tss;
    ivec3& yxy;
    ivec3& grg;
    ivec3& tst;
    ivec3& yxz;
    ivec3& grb;
    ivec3& tsu;
    ivec3& yyx;
    ivec3& ggr;
    ivec3& tts;
    ivec3& yyy;
    ivec3& ggg;
    ivec3& ttt;
    ivec3& yyz;
    ivec3& ggb;
    ivec3& ttu;
    ivec3& yzx;
    ivec3& gbr;
    ivec3& tus;
    ivec3& yzy;
    ivec3& gbg;
    ivec3& tut;
    ivec3& yzz;
    ivec3& gbb;
    ivec3& tuu;
    ivec3& zxx;
    ivec3& brr;
    ivec3& uss;
    ivec3& zxy;
    ivec3& brg;
    ivec3& ust;
    ivec3& zxz;
    ivec3& brb;
    ivec3& usu;
    ivec3& zyx;
    ivec3& bgr;
    ivec3& uts;
    ivec3& zyy;
    ivec3& bgg;
    ivec3& utt;
    ivec3& zyz;
    ivec3& bgb;
    ivec3& utu;
    ivec3& zzx;
    ivec3& bbr;
    ivec3& uus;
    ivec3& zzy;
    ivec3& bbg;
    ivec3& uut;
    ivec3& zzz;
    ivec3& bbb;
    ivec3& uuu;
    ivec3();
    explicit ivec3(int);
    ivec3(int, int, int);
    explicit ivec3(ivec2, int);
    explicit ivec3(int, ivec2);
    int operator[](const int);
    ivec3& operator=(const ivec3&);
    template<typename T> ivec3& operator+=(const T&);
    template<typename T> ivec3& operator-=(const T&);
    template<typename T> ivec3& operator*=(const T&);
    template<typename T> ivec3& operator/=(const T&);
};
ivec3 operator-(const ivec3&);
ivec3 operator+(const ivec3&, const ivec3&);
ivec3 operator-(const ivec3&, const ivec3&);
ivec3 operator*(const ivec3&, const ivec3&);
ivec3 operator/(const ivec3&, const ivec3&);
ivec3 operator+(const float&, const ivec3&);
ivec3 operator-(const float&, const ivec3&);
ivec3 operator*(const float&, const ivec3&);
ivec3 operator/(const float&, const ivec3&);
ivec3 operator+(const double&, const ivec3&);
ivec3 operator-(const double&, const ivec3&);
ivec3 operator*(const double&, const ivec3&);
ivec3 operator/(const double&, const ivec3&);
ivec3 operator+(const int&  , const ivec3&);
ivec3 operator-(const int&  , const ivec3&);
ivec3 operator*(const int&  , const ivec3&);
ivec3 operator/(const int&  , const ivec3&);
ivec3 operator+(const ivec3&, const float&);
ivec3 operator-(const ivec3&, const float&);
ivec3 operator*(const ivec3&, const float&);
ivec3 operator/(const ivec3&, const float&);
ivec3 operator+(const ivec3&, const double&);
ivec3 operator-(const ivec3&, const double&);
ivec3 operator*(const ivec3&, const double&);
ivec3 operator/(const ivec3&, const double&);
ivec3 operator+(const ivec3&, const int&  );
ivec3 operator-(const ivec3&, const int&  );
ivec3 operator*(const ivec3&, const int&  );
ivec3 operator/(const ivec3&, const int&  );
ivec3 refract(const ivec3&, const ivec3&, float);
ivec3 dFdx(const ivec3&);
ivec3 dFdy(const ivec3&);
ivec3 exp2(const ivec3&);
ivec3 clamp(const ivec3&, const ivec3&, const ivec3&);
ivec3 clamp(const ivec3&, const float&, const float&);
ivec3 sin(const ivec3&);
ivec3 cos(const ivec3&);struct ivec4 {
    static constexpr int dim=4;
    int x;
    int r;
    int s;
    int y;
    int g;
    int t;
    int z;
    int b;
    int u;
    int w;
    int a;
    int v;
    ivec2& xx;
    ivec2& rr;
    ivec2& ss;
    ivec2& xy;
    ivec2& rg;
    ivec2& st;
    ivec2& xz;
    ivec2& rb;
    ivec2& su;
    ivec2& xw;
    ivec2& ra;
    ivec2& sv;
    ivec2& yx;
    ivec2& gr;
    ivec2& ts;
    ivec2& yy;
    ivec2& gg;
    ivec2& tt;
    ivec2& yz;
    ivec2& gb;
    ivec2& tu;
    ivec2& yw;
    ivec2& ga;
    ivec2& tv;
    ivec2& zx;
    ivec2& br;
    ivec2& us;
    ivec2& zy;
    ivec2& bg;
    ivec2& ut;
    ivec2& zz;
    ivec2& bb;
    ivec2& uu;
    ivec2& zw;
    ivec2& ba;
    ivec2& uv;
    ivec2& wx;
    ivec2& ar;
    ivec2& vs;
    ivec2& wy;
    ivec2& ag;
    ivec2& vt;
    ivec2& wz;
    ivec2& ab;
    ivec2& vu;
    ivec2& ww;
    ivec2& aa;
    ivec2& vv;
    ivec3& xxx;
    ivec3& rrr;
    ivec3& sss;
    ivec3& xxy;
    ivec3& rrg;
    ivec3& sst;
    ivec3& xxz;
    ivec3& rrb;
    ivec3& ssu;
    ivec3& xxw;
    ivec3& rra;
    ivec3& ssv;
    ivec3& xyx;
    ivec3& rgr;
    ivec3& sts;
    ivec3& xyy;
    ivec3& rgg;
    ivec3& stt;
    ivec3& xyz;
    ivec3& rgb;
    ivec3& stu;
    ivec3& xyw;
    ivec3& rga;
    ivec3& stv;
    ivec3& xzx;
    ivec3& rbr;
    ivec3& sus;
    ivec3& xzy;
    ivec3& rbg;
    ivec3& sut;
    ivec3& xzz;
    ivec3& rbb;
    ivec3& suu;
    ivec3& xzw;
    ivec3& rba;
    ivec3& suv;
    ivec3& xwx;
    ivec3& rar;
    ivec3& svs;
    ivec3& xwy;
    ivec3& rag;
    ivec3& svt;
    ivec3& xwz;
    ivec3& rab;
    ivec3& svu;
    ivec3& xww;
    ivec3& raa;
    ivec3& svv;
    ivec3& yxx;
    ivec3& grr;
    ivec3& tss;
    ivec3& yxy;
    ivec3& grg;
    ivec3& tst;
    ivec3& yxz;
    ivec3& grb;
    ivec3& tsu;
    ivec3& yxw;
    ivec3& gra;
    ivec3& tsv;
    ivec3& yyx;
    ivec3& ggr;
    ivec3& tts;
    ivec3& yyy;
    ivec3& ggg;
    ivec3& ttt;
    ivec3& yyz;
    ivec3& ggb;
    ivec3& ttu;
    ivec3& yyw;
    ivec3& gga;
    ivec3& ttv;
    ivec3& yzx;
    ivec3& gbr;
    ivec3& tus;
    ivec3& yzy;
    ivec3& gbg;
    ivec3& tut;
    ivec3& yzz;
    ivec3& gbb;
    ivec3& tuu;
    ivec3& yzw;
    ivec3& gba;
    ivec3& tuv;
    ivec3& ywx;
    ivec3& gar;
    ivec3& tvs;
    ivec3& ywy;
    ivec3& gag;
    ivec3& tvt;
    ivec3& ywz;
    ivec3& gab;
    ivec3& tvu;
    ivec3& yww;
    ivec3& gaa;
    ivec3& tvv;
    ivec3& zxx;
    ivec3& brr;
    ivec3& uss;
    ivec3& zxy;
    ivec3& brg;
    ivec3& ust;
    ivec3& zxz;
    ivec3& brb;
    ivec3& usu;
    ivec3& zxw;
    ivec3& bra;
    ivec3& usv;
    ivec3& zyx;
    ivec3& bgr;
    ivec3& uts;
    ivec3& zyy;
    ivec3& bgg;
    ivec3& utt;
    ivec3& zyz;
    ivec3& bgb;
    ivec3& utu;
    ivec3& zyw;
    ivec3& bga;
    ivec3& utv;
    ivec3& zzx;
    ivec3& bbr;
    ivec3& uus;
    ivec3& zzy;
    ivec3& bbg;
    ivec3& uut;
    ivec3& zzz;
    ivec3& bbb;
    ivec3& uuu;
    ivec3& zzw;
    ivec3& bba;
    ivec3& uuv;
    ivec3& zwx;
    ivec3& bar;
    ivec3& uvs;
    ivec3& zwy;
    ivec3& bag;
    ivec3& uvt;
    ivec3& zwz;
    ivec3& bab;
    ivec3& uvu;
    ivec3& zww;
    ivec3& baa;
    ivec3& uvv;
    ivec3& wxx;
    ivec3& arr;
    ivec3& vss;
    ivec3& wxy;
    ivec3& arg;
    ivec3& vst;
    ivec3& wxz;
    ivec3& arb;
    ivec3& vsu;
    ivec3& wxw;
    ivec3& ara;
    ivec3& vsv;
    ivec3& wyx;
    ivec3& agr;
    ivec3& vts;
    ivec3& wyy;
    ivec3& agg;
    ivec3& vtt;
    ivec3& wyz;
    ivec3& agb;
    ivec3& vtu;
    ivec3& wyw;
    ivec3& aga;
    ivec3& vtv;
    ivec3& wzx;
    ivec3& abr;
    ivec3& vus;
    ivec3& wzy;
    ivec3& abg;
    ivec3& vut;
    ivec3& wzz;
    ivec3& abb;
    ivec3& vuu;
    ivec3& wzw;
    ivec3& aba;
    ivec3& vuv;
    ivec3& wwx;
    ivec3& aar;
    ivec3& vvs;
    ivec3& wwy;
    ivec3& aag;
    ivec3& vvt;
    ivec3& wwz;
    ivec3& aab;
    ivec3& vvu;
    ivec3& www;
    ivec3& aaa;
    ivec3& vvv;
    ivec4& xxxx;
    ivec4& rrrr;
    ivec4& ssss;
    ivec4& xxxy;
    ivec4& rrrg;
    ivec4& ssst;
    ivec4& xxxz;
    ivec4& rrrb;
    ivec4& sssu;
    ivec4& xxxw;
    ivec4& rrra;
    ivec4& sssv;
    ivec4& xxyx;
    ivec4& rrgr;
    ivec4& ssts;
    ivec4& xxyy;
    ivec4& rrgg;
    ivec4& sstt;
    ivec4& xxyz;
    ivec4& rrgb;
    ivec4& sstu;
    ivec4& xxyw;
    ivec4& rrga;
    ivec4& sstv;
    ivec4& xxzx;
    ivec4& rrbr;
    ivec4& ssus;
    ivec4& xxzy;
    ivec4& rrbg;
    ivec4& ssut;
    ivec4& xxzz;
    ivec4& rrbb;
    ivec4& ssuu;
    ivec4& xxzw;
    ivec4& rrba;
    ivec4& ssuv;
    ivec4& xxwx;
    ivec4& rrar;
    ivec4& ssvs;
    ivec4& xxwy;
    ivec4& rrag;
    ivec4& ssvt;
    ivec4& xxwz;
    ivec4& rrab;
    ivec4& ssvu;
    ivec4& xxww;
    ivec4& rraa;
    ivec4& ssvv;
    ivec4& xyxx;
    ivec4& rgrr;
    ivec4& stss;
    ivec4& xyxy;
    ivec4& rgrg;
    ivec4& stst;
    ivec4& xyxz;
    ivec4& rgrb;
    ivec4& stsu;
    ivec4& xyxw;
    ivec4& rgra;
    ivec4& stsv;
    ivec4& xyyx;
    ivec4& rggr;
    ivec4& stts;
    ivec4& xyyy;
    ivec4& rggg;
    ivec4& sttt;
    ivec4& xyyz;
    ivec4& rggb;
    ivec4& sttu;
    ivec4& xyyw;
    ivec4& rgga;
    ivec4& sttv;
    ivec4& xyzx;
    ivec4& rgbr;
    ivec4& stus;
    ivec4& xyzy;
    ivec4& rgbg;
    ivec4& stut;
    ivec4& xyzz;
    ivec4& rgbb;
    ivec4& stuu;
    ivec4& xyzw;
    ivec4& rgba;
    ivec4& stuv;
    ivec4& xywx;
    ivec4& rgar;
    ivec4& stvs;
    ivec4& xywy;
    ivec4& rgag;
    ivec4& stvt;
    ivec4& xywz;
    ivec4& rgab;
    ivec4& stvu;
    ivec4& xyww;
    ivec4& rgaa;
    ivec4& stvv;
    ivec4& xzxx;
    ivec4& rbrr;
    ivec4& suss;
    ivec4& xzxy;
    ivec4& rbrg;
    ivec4& sust;
    ivec4& xzxz;
    ivec4& rbrb;
    ivec4& susu;
    ivec4& xzxw;
    ivec4& rbra;
    ivec4& susv;
    ivec4& xzyx;
    ivec4& rbgr;
    ivec4& suts;
    ivec4& xzyy;
    ivec4& rbgg;
    ivec4& sutt;
    ivec4& xzyz;
    ivec4& rbgb;
    ivec4& sutu;
    ivec4& xzyw;
    ivec4& rbga;
    ivec4& sutv;
    ivec4& xzzx;
    ivec4& rbbr;
    ivec4& suus;
    ivec4& xzzy;
    ivec4& rbbg;
    ivec4& suut;
    ivec4& xzzz;
    ivec4& rbbb;
    ivec4& suuu;
    ivec4& xzzw;
    ivec4& rbba;
    ivec4& suuv;
    ivec4& xzwx;
    ivec4& rbar;
    ivec4& suvs;
    ivec4& xzwy;
    ivec4& rbag;
    ivec4& suvt;
    ivec4& xzwz;
    ivec4& rbab;
    ivec4& suvu;
    ivec4& xzww;
    ivec4& rbaa;
    ivec4& suvv;
    ivec4& xwxx;
    ivec4& rarr;
    ivec4& svss;
    ivec4& xwxy;
    ivec4& rarg;
    ivec4& svst;
    ivec4& xwxz;
    ivec4& rarb;
    ivec4& svsu;
    ivec4& xwxw;
    ivec4& rara;
    ivec4& svsv;
    ivec4& xwyx;
    ivec4& ragr;
    ivec4& svts;
    ivec4& xwyy;
    ivec4& ragg;
    ivec4& svtt;
    ivec4& xwyz;
    ivec4& ragb;
    ivec4& svtu;
    ivec4& xwyw;
    ivec4& raga;
    ivec4& svtv;
    ivec4& xwzx;
    ivec4& rabr;
    ivec4& svus;
    ivec4& xwzy;
    ivec4& rabg;
    ivec4& svut;
    ivec4& xwzz;
    ivec4& rabb;
    ivec4& svuu;
    ivec4& xwzw;
    ivec4& raba;
    ivec4& svuv;
    ivec4& xwwx;
    ivec4& raar;
    ivec4& svvs;
    ivec4& xwwy;
    ivec4& raag;
    ivec4& svvt;
    ivec4& xwwz;
    ivec4& raab;
    ivec4& svvu;
    ivec4& xwww;
    ivec4& raaa;
    ivec4& svvv;
    ivec4& yxxx;
    ivec4& grrr;
    ivec4& tsss;
    ivec4& yxxy;
    ivec4& grrg;
    ivec4& tsst;
    ivec4& yxxz;
    ivec4& grrb;
    ivec4& tssu;
    ivec4& yxxw;
    ivec4& grra;
    ivec4& tssv;
    ivec4& yxyx;
    ivec4& grgr;
    ivec4& tsts;
    ivec4& yxyy;
    ivec4& grgg;
    ivec4& tstt;
    ivec4& yxyz;
    ivec4& grgb;
    ivec4& tstu;
    ivec4& yxyw;
    ivec4& grga;
    ivec4& tstv;
    ivec4& yxzx;
    ivec4& grbr;
    ivec4& tsus;
    ivec4& yxzy;
    ivec4& grbg;
    ivec4& tsut;
    ivec4& yxzz;
    ivec4& grbb;
    ivec4& tsuu;
    ivec4& yxzw;
    ivec4& grba;
    ivec4& tsuv;
    ivec4& yxwx;
    ivec4& grar;
    ivec4& tsvs;
    ivec4& yxwy;
    ivec4& grag;
    ivec4& tsvt;
    ivec4& yxwz;
    ivec4& grab;
    ivec4& tsvu;
    ivec4& yxww;
    ivec4& graa;
    ivec4& tsvv;
    ivec4& yyxx;
    ivec4& ggrr;
    ivec4& ttss;
    ivec4& yyxy;
    ivec4& ggrg;
    ivec4& ttst;
    ivec4& yyxz;
    ivec4& ggrb;
    ivec4& ttsu;
    ivec4& yyxw;
    ivec4& ggra;
    ivec4& ttsv;
    ivec4& yyyx;
    ivec4& gggr;
    ivec4& ttts;
    ivec4& yyyy;
    ivec4& gggg;
    ivec4& tttt;
    ivec4& yyyz;
    ivec4& gggb;
    ivec4& tttu;
    ivec4& yyyw;
    ivec4& ggga;
    ivec4& tttv;
    ivec4& yyzx;
    ivec4& ggbr;
    ivec4& ttus;
    ivec4& yyzy;
    ivec4& ggbg;
    ivec4& ttut;
    ivec4& yyzz;
    ivec4& ggbb;
    ivec4& ttuu;
    ivec4& yyzw;
    ivec4& ggba;
    ivec4& ttuv;
    ivec4& yywx;
    ivec4& ggar;
    ivec4& ttvs;
    ivec4& yywy;
    ivec4& ggag;
    ivec4& ttvt;
    ivec4& yywz;
    ivec4& ggab;
    ivec4& ttvu;
    ivec4& yyww;
    ivec4& ggaa;
    ivec4& ttvv;
    ivec4& yzxx;
    ivec4& gbrr;
    ivec4& tuss;
    ivec4& yzxy;
    ivec4& gbrg;
    ivec4& tust;
    ivec4& yzxz;
    ivec4& gbrb;
    ivec4& tusu;
    ivec4& yzxw;
    ivec4& gbra;
    ivec4& tusv;
    ivec4& yzyx;
    ivec4& gbgr;
    ivec4& tuts;
    ivec4& yzyy;
    ivec4& gbgg;
    ivec4& tutt;
    ivec4& yzyz;
    ivec4& gbgb;
    ivec4& tutu;
    ivec4& yzyw;
    ivec4& gbga;
    ivec4& tutv;
    ivec4& yzzx;
    ivec4& gbbr;
    ivec4& tuus;
    ivec4& yzzy;
    ivec4& gbbg;
    ivec4& tuut;
    ivec4& yzzz;
    ivec4& gbbb;
    ivec4& tuuu;
    ivec4& yzzw;
    ivec4& gbba;
    ivec4& tuuv;
    ivec4& yzwx;
    ivec4& gbar;
    ivec4& tuvs;
    ivec4& yzwy;
    ivec4& gbag;
    ivec4& tuvt;
    ivec4& yzwz;
    ivec4& gbab;
    ivec4& tuvu;
    ivec4& yzww;
    ivec4& gbaa;
    ivec4& tuvv;
    ivec4& ywxx;
    ivec4& garr;
    ivec4& tvss;
    ivec4& ywxy;
    ivec4& garg;
    ivec4& tvst;
    ivec4& ywxz;
    ivec4& garb;
    ivec4& tvsu;
    ivec4& ywxw;
    ivec4& gara;
    ivec4& tvsv;
    ivec4& ywyx;
    ivec4& gagr;
    ivec4& tvts;
    ivec4& ywyy;
    ivec4& gagg;
    ivec4& tvtt;
    ivec4& ywyz;
    ivec4& gagb;
    ivec4& tvtu;
    ivec4& ywyw;
    ivec4& gaga;
    ivec4& tvtv;
    ivec4& ywzx;
    ivec4& gabr;
    ivec4& tvus;
    ivec4& ywzy;
    ivec4& gabg;
    ivec4& tvut;
    ivec4& ywzz;
    ivec4& gabb;
    ivec4& tvuu;
    ivec4& ywzw;
    ivec4& gaba;
    ivec4& tvuv;
    ivec4& ywwx;
    ivec4& gaar;
    ivec4& tvvs;
    ivec4& ywwy;
    ivec4& gaag;
    ivec4& tvvt;
    ivec4& ywwz;
    ivec4& gaab;
    ivec4& tvvu;
    ivec4& ywww;
    ivec4& gaaa;
    ivec4& tvvv;
    ivec4& zxxx;
    ivec4& brrr;
    ivec4& usss;
    ivec4& zxxy;
    ivec4& brrg;
    ivec4& usst;
    ivec4& zxxz;
    ivec4& brrb;
    ivec4& ussu;
    ivec4& zxxw;
    ivec4& brra;
    ivec4& ussv;
    ivec4& zxyx;
    ivec4& brgr;
    ivec4& usts;
    ivec4& zxyy;
    ivec4& brgg;
    ivec4& ustt;
    ivec4& zxyz;
    ivec4& brgb;
    ivec4& ustu;
    ivec4& zxyw;
    ivec4& brga;
    ivec4& ustv;
    ivec4& zxzx;
    ivec4& brbr;
    ivec4& usus;
    ivec4& zxzy;
    ivec4& brbg;
    ivec4& usut;
    ivec4& zxzz;
    ivec4& brbb;
    ivec4& usuu;
    ivec4& zxzw;
    ivec4& brba;
    ivec4& usuv;
    ivec4& zxwx;
    ivec4& brar;
    ivec4& usvs;
    ivec4& zxwy;
    ivec4& brag;
    ivec4& usvt;
    ivec4& zxwz;
    ivec4& brab;
    ivec4& usvu;
    ivec4& zxww;
    ivec4& braa;
    ivec4& usvv;
    ivec4& zyxx;
    ivec4& bgrr;
    ivec4& utss;
    ivec4& zyxy;
    ivec4& bgrg;
    ivec4& utst;
    ivec4& zyxz;
    ivec4& bgrb;
    ivec4& utsu;
    ivec4& zyxw;
    ivec4& bgra;
    ivec4& utsv;
    ivec4& zyyx;
    ivec4& bggr;
    ivec4& utts;
    ivec4& zyyy;
    ivec4& bggg;
    ivec4& uttt;
    ivec4& zyyz;
    ivec4& bggb;
    ivec4& uttu;
    ivec4& zyyw;
    ivec4& bgga;
    ivec4& uttv;
    ivec4& zyzx;
    ivec4& bgbr;
    ivec4& utus;
    ivec4& zyzy;
    ivec4& bgbg;
    ivec4& utut;
    ivec4& zyzz;
    ivec4& bgbb;
    ivec4& utuu;
    ivec4& zyzw;
    ivec4& bgba;
    ivec4& utuv;
    ivec4& zywx;
    ivec4& bgar;
    ivec4& utvs;
    ivec4& zywy;
    ivec4& bgag;
    ivec4& utvt;
    ivec4& zywz;
    ivec4& bgab;
    ivec4& utvu;
    ivec4& zyww;
    ivec4& bgaa;
    ivec4& utvv;
    ivec4& zzxx;
    ivec4& bbrr;
    ivec4& uuss;
    ivec4& zzxy;
    ivec4& bbrg;
    ivec4& uust;
    ivec4& zzxz;
    ivec4& bbrb;
    ivec4& uusu;
    ivec4& zzxw;
    ivec4& bbra;
    ivec4& uusv;
    ivec4& zzyx;
    ivec4& bbgr;
    ivec4& uuts;
    ivec4& zzyy;
    ivec4& bbgg;
    ivec4& uutt;
    ivec4& zzyz;
    ivec4& bbgb;
    ivec4& uutu;
    ivec4& zzyw;
    ivec4& bbga;
    ivec4& uutv;
    ivec4& zzzx;
    ivec4& bbbr;
    ivec4& uuus;
    ivec4& zzzy;
    ivec4& bbbg;
    ivec4& uuut;
    ivec4& zzzz;
    ivec4& bbbb;
    ivec4& uuuu;
    ivec4& zzzw;
    ivec4& bbba;
    ivec4& uuuv;
    ivec4& zzwx;
    ivec4& bbar;
    ivec4& uuvs;
    ivec4& zzwy;
    ivec4& bbag;
    ivec4& uuvt;
    ivec4& zzwz;
    ivec4& bbab;
    ivec4& uuvu;
    ivec4& zzww;
    ivec4& bbaa;
    ivec4& uuvv;
    ivec4& zwxx;
    ivec4& barr;
    ivec4& uvss;
    ivec4& zwxy;
    ivec4& barg;
    ivec4& uvst;
    ivec4& zwxz;
    ivec4& barb;
    ivec4& uvsu;
    ivec4& zwxw;
    ivec4& bara;
    ivec4& uvsv;
    ivec4& zwyx;
    ivec4& bagr;
    ivec4& uvts;
    ivec4& zwyy;
    ivec4& bagg;
    ivec4& uvtt;
    ivec4& zwyz;
    ivec4& bagb;
    ivec4& uvtu;
    ivec4& zwyw;
    ivec4& baga;
    ivec4& uvtv;
    ivec4& zwzx;
    ivec4& babr;
    ivec4& uvus;
    ivec4& zwzy;
    ivec4& babg;
    ivec4& uvut;
    ivec4& zwzz;
    ivec4& babb;
    ivec4& uvuu;
    ivec4& zwzw;
    ivec4& baba;
    ivec4& uvuv;
    ivec4& zwwx;
    ivec4& baar;
    ivec4& uvvs;
    ivec4& zwwy;
    ivec4& baag;
    ivec4& uvvt;
    ivec4& zwwz;
    ivec4& baab;
    ivec4& uvvu;
    ivec4& zwww;
    ivec4& baaa;
    ivec4& uvvv;
    ivec4& wxxx;
    ivec4& arrr;
    ivec4& vsss;
    ivec4& wxxy;
    ivec4& arrg;
    ivec4& vsst;
    ivec4& wxxz;
    ivec4& arrb;
    ivec4& vssu;
    ivec4& wxxw;
    ivec4& arra;
    ivec4& vssv;
    ivec4& wxyx;
    ivec4& argr;
    ivec4& vsts;
    ivec4& wxyy;
    ivec4& argg;
    ivec4& vstt;
    ivec4& wxyz;
    ivec4& argb;
    ivec4& vstu;
    ivec4& wxyw;
    ivec4& arga;
    ivec4& vstv;
    ivec4& wxzx;
    ivec4& arbr;
    ivec4& vsus;
    ivec4& wxzy;
    ivec4& arbg;
    ivec4& vsut;
    ivec4& wxzz;
    ivec4& arbb;
    ivec4& vsuu;
    ivec4& wxzw;
    ivec4& arba;
    ivec4& vsuv;
    ivec4& wxwx;
    ivec4& arar;
    ivec4& vsvs;
    ivec4& wxwy;
    ivec4& arag;
    ivec4& vsvt;
    ivec4& wxwz;
    ivec4& arab;
    ivec4& vsvu;
    ivec4& wxww;
    ivec4& araa;
    ivec4& vsvv;
    ivec4& wyxx;
    ivec4& agrr;
    ivec4& vtss;
    ivec4& wyxy;
    ivec4& agrg;
    ivec4& vtst;
    ivec4& wyxz;
    ivec4& agrb;
    ivec4& vtsu;
    ivec4& wyxw;
    ivec4& agra;
    ivec4& vtsv;
    ivec4& wyyx;
    ivec4& aggr;
    ivec4& vtts;
    ivec4& wyyy;
    ivec4& aggg;
    ivec4& vttt;
    ivec4& wyyz;
    ivec4& aggb;
    ivec4& vttu;
    ivec4& wyyw;
    ivec4& agga;
    ivec4& vttv;
    ivec4& wyzx;
    ivec4& agbr;
    ivec4& vtus;
    ivec4& wyzy;
    ivec4& agbg;
    ivec4& vtut;
    ivec4& wyzz;
    ivec4& agbb;
    ivec4& vtuu;
    ivec4& wyzw;
    ivec4& agba;
    ivec4& vtuv;
    ivec4& wywx;
    ivec4& agar;
    ivec4& vtvs;
    ivec4& wywy;
    ivec4& agag;
    ivec4& vtvt;
    ivec4& wywz;
    ivec4& agab;
    ivec4& vtvu;
    ivec4& wyww;
    ivec4& agaa;
    ivec4& vtvv;
    ivec4& wzxx;
    ivec4& abrr;
    ivec4& vuss;
    ivec4& wzxy;
    ivec4& abrg;
    ivec4& vust;
    ivec4& wzxz;
    ivec4& abrb;
    ivec4& vusu;
    ivec4& wzxw;
    ivec4& abra;
    ivec4& vusv;
    ivec4& wzyx;
    ivec4& abgr;
    ivec4& vuts;
    ivec4& wzyy;
    ivec4& abgg;
    ivec4& vutt;
    ivec4& wzyz;
    ivec4& abgb;
    ivec4& vutu;
    ivec4& wzyw;
    ivec4& abga;
    ivec4& vutv;
    ivec4& wzzx;
    ivec4& abbr;
    ivec4& vuus;
    ivec4& wzzy;
    ivec4& abbg;
    ivec4& vuut;
    ivec4& wzzz;
    ivec4& abbb;
    ivec4& vuuu;
    ivec4& wzzw;
    ivec4& abba;
    ivec4& vuuv;
    ivec4& wzwx;
    ivec4& abar;
    ivec4& vuvs;
    ivec4& wzwy;
    ivec4& abag;
    ivec4& vuvt;
    ivec4& wzwz;
    ivec4& abab;
    ivec4& vuvu;
    ivec4& wzww;
    ivec4& abaa;
    ivec4& vuvv;
    ivec4& wwxx;
    ivec4& aarr;
    ivec4& vvss;
    ivec4& wwxy;
    ivec4& aarg;
    ivec4& vvst;
    ivec4& wwxz;
    ivec4& aarb;
    ivec4& vvsu;
    ivec4& wwxw;
    ivec4& aara;
    ivec4& vvsv;
    ivec4& wwyx;
    ivec4& aagr;
    ivec4& vvts;
    ivec4& wwyy;
    ivec4& aagg;
    ivec4& vvtt;
    ivec4& wwyz;
    ivec4& aagb;
    ivec4& vvtu;
    ivec4& wwyw;
    ivec4& aaga;
    ivec4& vvtv;
    ivec4& wwzx;
    ivec4& aabr;
    ivec4& vvus;
    ivec4& wwzy;
    ivec4& aabg;
    ivec4& vvut;
    ivec4& wwzz;
    ivec4& aabb;
    ivec4& vvuu;
    ivec4& wwzw;
    ivec4& aaba;
    ivec4& vvuv;
    ivec4& wwwx;
    ivec4& aaar;
    ivec4& vvvs;
    ivec4& wwwy;
    ivec4& aaag;
    ivec4& vvvt;
    ivec4& wwwz;
    ivec4& aaab;
    ivec4& vvvu;
    ivec4& wwww;
    ivec4& aaaa;
    ivec4& vvvv;
    ivec4();
    explicit ivec4(int);
    ivec4(int, int, int, int);
    explicit ivec4(ivec3, int);
    explicit ivec4(int, ivec3);
    explicit ivec4(ivec2, int, int);
    explicit ivec4(int, ivec2, int);
    explicit ivec4(int, int, ivec2);
    int operator[](const int);
    ivec4& operator=(const ivec4&);
    template<typename T> ivec4& operator+=(const T&);
    template<typename T> ivec4& operator-=(const T&);
    template<typename T> ivec4& operator*=(const T&);
    template<typename T> ivec4& operator/=(const T&);
};
ivec4 operator-(const ivec4&);
ivec4 operator+(const ivec4&, const ivec4&);
ivec4 operator-(const ivec4&, const ivec4&);
ivec4 operator*(const ivec4&, const ivec4&);
ivec4 operator/(const ivec4&, const ivec4&);
ivec4 operator+(const float&, const ivec4&);
ivec4 operator-(const float&, const ivec4&);
ivec4 operator*(const float&, const ivec4&);
ivec4 operator/(const float&, const ivec4&);
ivec4 operator+(const double&, const ivec4&);
ivec4 operator-(const double&, const ivec4&);
ivec4 operator*(const double&, const ivec4&);
ivec4 operator/(const double&, const ivec4&);
ivec4 operator+(const int&  , const ivec4&);
ivec4 operator-(const int&  , const ivec4&);
ivec4 operator*(const int&  , const ivec4&);
ivec4 operator/(const int&  , const ivec4&);
ivec4 operator+(const ivec4&, const float&);
ivec4 operator-(const ivec4&, const float&);
ivec4 operator*(const ivec4&, const float&);
ivec4 operator/(const ivec4&, const float&);
ivec4 operator+(const ivec4&, const double&);
ivec4 operator-(const ivec4&, const double&);
ivec4 operator*(const ivec4&, const double&);
ivec4 operator/(const ivec4&, const double&);
ivec4 operator+(const ivec4&, const int&  );
ivec4 operator-(const ivec4&, const int&  );
ivec4 operator*(const ivec4&, const int&  );
ivec4 operator/(const ivec4&, const int&  );
ivec4 refract(const ivec4&, const ivec4&, float);
ivec4 dFdx(const ivec4&);
ivec4 dFdy(const ivec4&);
ivec4 exp2(const ivec4&);
ivec4 clamp(const ivec4&, const ivec4&, const ivec4&);
ivec4 clamp(const ivec4&, const float&, const float&);
ivec4 sin(const ivec4&);
ivec4 cos(const ivec4&);
// clang-format on

// keywords
#define uniform
#define in
#define out
#define inout
#define attribute
#define discard abort()
#define layout(...)
void EmitVertex();
void EndPrimitive();

// matx
struct mat3 {};
struct mat4 {};

// gl_*
vec4 gl_FragData[8];
vec4 gl_FragColor;
vec4 gl_Position;
vec4 gl_MultiTexCoord0, gl_MultiTexCoord1;
vec4 gl_Normal, gl_Color;
vec4 ftransform();
vec4 gl_Vertex;
mat3 gl_NormalMatrix;
mat4 gl_ModelViewMatrix, gl_ProjectionMatrix;
mat4 *gl_TextureMatrix;
struct gl_PerVertex {
    vec4 gl_Position;
    float gl_PointSize;
    float *gl_ClipDistance;
};
gl_PerVertex *gl_in;

// texture type
struct sampler2D {};
struct sampler2DShadow {};
vec4 texture2D(sampler2D, vec2);
vec4 texture2D(sampler2D, vec2, float);
vec4 texture2D(sampler2DShadow, vec2);
vec4 texture2D(sampler2DShadow, vec2, float);
vec4 texture2DLod(sampler2D, vec2, int);
vec4 texture2DLod(sampler2DShadow, vec2, int);
vec4 shadow2DLod(sampler2D, vec3, int);
vec4 shadow2DLod(sampler2DShadow, vec3, int);

// matx * vecx
vec4 operator*(mat4, vec4);
vec3 operator*(mat3, vec3);

#include <concepts>
#include <type_traits>
template <typename T>
concept float_like = requires(T a) {
    std::is_floating_point_v<T>;
};
template <typename T>
concept vec_like = requires(T a) {
    std::is_same_v<T, vec2> || std::is_same_v<T, vec3> || std::is_same_v<T, vec4>;
};
template <typename T>
concept ivec_like = requires(T a) {
    std::is_same_v<T, ivec2> || std::is_same_v<T, ivec3> || std::is_same_v<T, ivec4>;
};
template <typename T>
concept xvec_like = requires(T a) {
    std::is_same_v<T, vec2> || std::is_same_v<T, vec3> || std::is_same_v<T, vec4> || std::is_same_v<T, ivec2> || std::is_same_v<T, ivec3> || std::is_same_v<T, ivec4>;
};
template <typename T, typename V>
concept same_dim = requires(T a, V b) {
    xvec_like<T> &&xvec_like<V> &&T::dim == V::dim;
};
template <typename T, typename V, typename...>
concept same_dim = requires(T a, V b) {
    xvec_like<T> &&xvec_like<V> &&T::dim == V::dim;
};

// clang-format off

// float like defs
template<float_like T> int floor(T);
template<float_like T> T fract(T);
template<float_like T, float_like V> float mod(T, V);
template<float_like T, float_like V> float pow(T, V);
template<float_like T, float_like V> float min(T, V);
template<float_like T, float_like V> float max(T, V);
template<float_like T, float_like V> float step(T, V);
template<float_like T, float_like V, float_like P> float mix(T, V, P);
template<float_like T, float_like V, float_like P> float clamp(T, V, P);

// vec like defs
template<vec_like T> T floor(T);
template<vec_like T> T fract(T);
template<vec_like T> T normalize(T);
template<vec_like T, typename V> T mod(T, V) requires float_like<V>||same_dim<T, V>;
template<vec_like T, vec_like V> T pow(T, V) requires same_dim<T, V>;
template<vec_like T, typename V> T min(T, V) requires float_like<V>||same_dim<T, V>;
template<vec_like T, typename V> T max(T, V) requires float_like<V>||same_dim<T, V>;
template<vec_like T, xvec_like V> T step(T, V) requires same_dim<T, V>;
template<vec_like T, vec_like V, typename P> T mix(T, V, P) requires same_dim<T, V> && (float_like<P>||same_dim<V, P>);
template<vec_like T, typename V, typename P> float clamp(T, V, P) requires (float_like<P>&&float_like<V>)||(same_dim<V,P>&&same_dim<T,V>);

template<typename T> T sin(T) requires float_like<T>||vec_like<T>;
template<typename T> T cos(T) requires float_like<T>||vec_like<T>;
template<typename T> T exp2(T) requires float_like<T>||vec_like<T>;

// single arg defs
template<typename T> T sqrt(T);
template<typename T> T abs(T);
template<typename T> T sign(T);
// clang-format on

float length(vec2);
float length(vec3);
vec3 cross(vec3, vec3);
float dot(vec3, vec3);
float dot(vec2, vec2);
float distance(vec3, vec3);
#endif
#endif